const dares = [
    "Do 10 push-ups right now.",
    "Dance for 40 seconds without any music.",
    "Send a text saying 'I know what uou did last week...' to a random phone number.",
    "Take a selfie with a random person.",
    "Ask a stranger for a hug.",
    "Ask a stranger if they know where the closest gay bar is.",
    "Do 10 squats right now.",
    "Run as fast as you can to the nearest toilet.",
    "Do an interpretive dance of a household chore.",
    "Ask a stranger to take a photo of you with random people.",
    "Try to convince a stranger they've met you before",
    "Speak to a stranger in a thick accent.",
    "Ask a stranger to help you practice your handshake ideas",
    "Propose to a stranger.",
    "Ask a stranger if they saw the aliens last night",
    "Challenge a stranger to a staring contest",
    "Ask a staffer for the secret menu. Insist you know they have one.",
    "Attempt to sell something to a stranger",
    "Stand up and conduct an invisible orchestra for 25 seconds.",
    "Ask a stranger to taste their drink.",
    "Ask a stranger if they're alright, and mention that they looked a little down.",
    "Enthusiasically prompt a stranger for a high-five.",
    "Ask a stranger to join the game.",
    "Scream loudly, as though receiving a sudden big fright.",
    "Confess sin to a stranger.",
    "Introduce yourself to a stranger, saying 'I can tell a fellow Elvis fan anywhere'.",
    "Take a new profile picture right now, and set it for 24hrs.",
    "Post 'I ❤️ Nickelback' on all socials for 24 hours.",
    "Set your phone language to Chinese, close the settings, and return to your home screen.",
    "Do the moonwalk across the room.",
    "Do the worm.",
    "Do the robot.",
    "Phone a random number and ask to order food.",
    "Phone a random number and ask for a date.",
    "Phone a random number and ask for a job.",
    "Phone a random number and ask for a loan.",
    "Walk backwards to the end of the room and back.",
    "Celebrate as though you've just won big.",
    "Mix all available liquids together and drink it.",
    "Show your most recently taken photos.",
    "Keep your eyes closed until it’s your go again.",
    "Show off your orgasm face.",
    "Jump up and down as high as you can 8 times.",
];
