const truths = [
    "What secret would you take to your grave?",
    "What is your biggest fear?",
    "What is the most embarrassing thing you've ever done?",
    "If you could switch lives with someone for a day, who would it be, and why?",
    "What is your guiltiest pleasure?",
    "What is the most childish thing you still do?",
    "Tell about the last time you cried.",
    "Tell about the most disgusting thing you've ever done.",
    "What's the most illegal thing you've gotten away with?",
    "What's the biggest lie you've told your parents?",
    "What's the most embarrassing thing your parents caught you doing?",
    "What's the pettiest reason you've ever held a grudge?",
    "What celebrity would make you question your relationship?",
    "What's your most controversial 'hot take'?",
    "What's the most cringey phase you went through?",
    "What's your 'I will deny this if asked' opinion?",
    "What do you find weirdly attractive?",
    "What's the most awkward thing you've done to impress someone?",
    "What's the pettiest thing you've ever revenge-planned?",
    "What's your 'I can't believe I survived that' story?",
    "What's the most questionable item in your trash right now?",
    "What's the most questionable item in your room right now?",
    "Tell about the strangest dream you've ever had",
    "What's your most irrational fear?",
    "What's the worst thing you've done while drunk/high?",
    "What's your 'I'm never doing that again' sexual experience?",
    "What's the worst thing you've done to a friend's belongings?",
    "What's your most shameful 'guilty pleasure' entertainment?",
    "What's the most cringey thing in your social media history?",
    "What's your 'I still feel bad about this' childhood cruelty?",
    "What's the most NSFW thing you've done at work/school?",
    "What's the most embarrassing medical issue you've hidden?",
    "What's the weirdest thing you've collected/still collect?",
    "What's the most embarrassing thing you've done for love?",
    "What's your worst hygiene habit?",
    "What's your most controversial food opinion?",
    "What's the strangest place you've hooked up/masturbated?",
    "What's the most embarrassing thing you've been caught singing?",
    "What's your biggest 'I immediately regret this' purchase?",
    "What's the worst gift you've ever regifted?",
    "What's your 'I pretended to like this way too long' secret?",
    "What's the most embarrassing thing you've done for money?",
    "What's the most embarrassing thing you've Googled this week?",
    "What's the most NSFW thing you've done in a public place?",
    "What's the pettiest thing you've been competitive about?",
    "Who's your biggest celebrity crush?",
    "What's the worst thing you've done to avoid confrontation?",
    "What's the most embarrassing thing you've posted online?",
    "What's your 'I'm still mad about this' childhood injustice?",
    "What's your 'I can't believe I used to think this' opinion?",
    "What's the worst thing you've eaten off the floor?",
    "What's your most irrational superstition?",
    "What's the strangest lie you've told to seem interesting?",
    "What's the most embarrassing thing you've done for clout?",
    "What's your secret hobby that would surprise everyone?",
    "What's your 'I know this makes me a bad person' confession?",
    "What's the strangest thing you've been sexually attracted to?",
    "What's your 'I thought this was normal until...' realization?",
    "What's the most embarrassing thing you've done for attention?",
    "What's your most shameful 'guilty pleasure' song?",
    "What's the most embarrassing thing you've done while drunk?",
    "What's your 'I still cringe when I think about this' memory?",
    "What's the strangest place you've fallen asleep?",
    "What's the weirdest thing you've done while bored?",
    "Explain one of your hypocricies.",
    "What's the most embarrassing thing you've pretended to like?",
    "What's your 'I should have known better' relationship story?",
    "What's the strangest thing you've cried over?",
    "What's the worst advice you've ever given someone?",
    "What's the weirdest thing you've done to avoid human interaction?",
    "What's your most shameful habit?",
    "What’s the worst thing you’ve ever done at work?",
    "When’s the last time you made someone else cry?",
    "What are your favorite and least favorite of your body parts?",
    "If you switched genders for a day, what would you do?",
    "What bridges are you glad that you burned?",
    "What’s the meanest thing you’ve ever said to someone else?",
    "What’s the last lie you told?",  
];
